Updates 0218
WildCodeSchool/simple-mvc-old-caprover pull request #4
Opened 2018-03-26 15:58 UTC by AurelienBarbier

2018-03-26 21:02 UTC, sblondeau requested changes

2018-03-26 21:02 UTC, sblondeau commented on app/Connection.php
> +            $this->_pdoConnection = new PDO(
non! pas de "_" devant les noms de propriétés ! c'est pas PSR :p

2018-03-26 21:02 UTC, sblondeau commented on app/config.php
> +define('APP_VIEW_PATH', __DIR__.'/../src/View/');
il faut bien laisser des espaces (PSR) de part et d'autres de l'opérateur de concaténation.
donc `__DIR___ . '/../src/View'`

2018-03-26 21:02 UTC, sblondeau commented on app/dispatcher.php
> +        $class = APP_CONTROLLER_NAMESPACE.$class.APP_CONTROLLER_SUFFIX;
pareil, remets les espaces

2018-03-26 21:02 UTC, sblondeau commented on app/dispatcher.php
> +        echo call_user_func_array(array(new $class(), $method), $vars);
un petit [] au lieu de array() ?

2018-03-26 21:02 UTC, sblondeau commented on src/Model/AbstractManager.php
> +        $this->className = __NAMESPACE__.'\\'.ucfirst($table);
encore les espaces :p

2018-03-27 06:46 UTC, AurelienBarbier commented on app/Connection.php
> +            $this->_pdoConnection = new PDO(
Il me semblait avoir virée tous les `_`, et vu que code sniffer ne me disait plus rien...ok, je revois ça.

2018-03-27 11:50 UTC, sblondeau approved these changes

2018-03-27 11:50 UTC, merged