Pdo connection improvement
WildCodeSchool/simple-mvc-old-caprover pull request #7
Opened 2018-09-20 07:22 UTC by AurelienBarbier

2018-09-20 11:04 UTC, sblondeau requested changes

2018-09-20 11:04 UTC, sblondeau commented on src/Model/AbstractManager.php
> +    public function __construct(string $table, PDO $pdo)
\PDO et pas PDO

2018-09-20 11:04 UTC, sblondeau commented on src/Controller/ItemController.php
> +            if (false !== $id = $itemManager->insert($item)) {
j'aime pas trop comme ça,  je ne trouve pas cette façon d'écrire très claire
je préférerais un try/catch avec une exception si l'insert s'est pas bien passé. 
Ou alors on ne teste pas du tout l'erreur dans l'exemple sur le simple mvc pour pas rajouter de complexité supplémentaire ?

2018-09-21 09:04 UTC, open-it requested changes
A discuter, j'ai fais 2 petits retours

2018-09-21 09:04 UTC, open-it commented on src/Controller/ItemController.php
> +        $itemManager = new ItemManager($this->pdo);
J'utiliserai le getter pour respecter l'encapsulation

2018-09-21 09:04 UTC, open-it commented on src/Model/ItemManager.php
> +    public function __construct($pdo)
le typage du paramètre est omis.

2018-09-21 12:31 UTC, AurelienBarbier commented on src/Controller/ItemController.php
> +        $itemManager = new ItemManager($this->pdo);
ça te semble plus pertinent qu'à l'instanciation ?

2018-09-26 15:05 UTC, sblondeau approved these changes

2018-10-01 09:37 UTC, open-it approved these changes

2018-10-01 09:37 UTC, merged